# Dependencies
markdown:         kramdown
highlighter:      pygments

# Gems
gems:            [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            'from data to scholarship'
tagline:          ''
description:      'musings on history, religion, and computers'
url:              
baseurl:          /

author:
  name:           'Jeri E. Wieringa'
  url:            https://twitter.com/jerielizabeth

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jerielizabeth

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/