# Dependencies
markdown:         kramdown
highlighter:      rouge

# Gems
gems:            [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            'from data to scholarship'
tagline:          ''
description:      'musings on history, religion, and computers'
url:              
baseurl:          ''

author:
  name:           'Jeri E. Wieringa'
  url:            https://twitter.com/jerielizabeth
  email:          'mailto:jeri.elizabeth@gmail.com'
  ko-fi:          https://ko-fi.com/I2I296JA

paginate:         3
timezone:         'America/Los_Angeles'
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jerielizabeth

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/